version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: ./backend  
    environment:
      - REDIS_HOST=redis
    ports:
      - "9900:9900"  
    depends_on:
      - redis  

  frontend:
    build: ./frontend 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9900 
    ports:
      - "3901:3000" 
    depends_on:
      - app  

